### ISSUE TITLE
Please use bool instead of boolean

### ISSUE THREAD

**Issue by FastThenLeft** [liffiton/Arduino-Cheat-Sheet#5]
I love this cheat sheet. It's the best I've found. I use it to teach my microcontroller classes.

However, you use "boolean" as the data type in the "Variables, Arrays, and Data" section. It should be "bool". Arduino has depreciated "boolean" a long time ago. See: https://www.arduino.cc/reference/en/language/variables/data-types/boolean/

**Comment by liffiton** [comment]
Thanks for the feedback.  I'm so glad you've found it useful.

And thanks for the correction!

**Comment by FastThenLeft** [comment]
You are more than welcome. Thank *you* for your work putting this together!
